name: Docker Image CI for Docker Hub

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # 指定为 22.04 的稳定版本
    strategy:
      matrix:
        platform: [ 'linux/amd64', 'linux/arm64', 'linux/arm' ]  # 使用 Matrix 策略构建多个平台

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set build date
      id: date
      run: echo "BUILD_DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV  # 设置构建日期为 year.month.date

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          neowitch/cockpit  # 使用你的 Docker Hub 用户名和项目名称
        tags: |
          type=raw,value=${{ env.BUILD_DATE }}  # 使用日期作为标签
          type=raw,value=latest  # 同时使用 latest 标签

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}  # 在 GitHub Secrets 中设置
        password: ${{ secrets.DOCKER_PASSWORD }}  # 在 GitHub Secrets 中设置

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm  # 直接指定多个平台
        push: true
        tags: ${{ steps.meta.outputs.tags }}  # 使用日期和 latest 标签
        labels: ${{ steps.meta.outputs.labels }}
